### ISSUE TITLE
Can't select element to relate to from modal

### ISSUE THREAD

**Issue by svale** [verbb/many-to-many#24] opened 2019-03-04 21:25 UTC
Hi! 

When trying to add a (reverse) relationship from a Many to Many field, the element select modal opens up empty (no elements to select from).

Probably because of changes introduces in Craft 3.1, ref: https://craftcms.com/guides/updating-plugins-for-craft-3-1#update-element-source-key-references

So it seems this is easily fixed by changing 
```
'section' => $relatedSection->id
``` 
to
```
'section' => $relatedSection->uid
```
in `craft-manytomany/src/fields/ManyToManyField.php`> `getInputHtml()`

Thank you for providing a nice plugin!

---
Craft 3.1.15 with project.yaml

**Comment by alexrubin** [comment] 2019-03-07 19:11
I have this issue as well.

**Comment by bertheyman** [comment] 2019-05-15 06:57
@svale : this was recently fixed, so you might want to try again if it's working for you now :)

**Comment by matthisamoto** [comment] 2019-08-27 21:19
I am also having this issue currently on M2M v1.0.2.2 attempting to inversely relate an entry to an entry directly, not through categories but by using an Entries field as the Associated Field.

I just updated to Craft 3.3 and I do not know if this was working/not working as intended before I did that.

**Comment by engram-design** [comment] 2022-11-24 02:10
Fixed in [2.0.0](https://github.com/verbb/many-to-many/releases/tag/2.0.0)

**Closed by engram-design** 2022-11-24 02:10 UTC
Labels: bug
